version: '3.5'

services:
  boilerplate-web:
    build:
      context: boilerplate
      dockerfile: Dockerfile
    env_file: boilerplate/.env
    tty: true
    volumes:
      - ./boilerplate/:/code/
    ports:
      - "8000:8000"
    networks:
      - boilerplate_net

  boilerplate-db:
    build:
      context: db
      dockerfile: Dockerfile
    env_file: db/.env     
    networks:
      - boilerplate_net
    
  boilerplate-redis:
    image: "redis:5.0.7-alpine"   
    networks:
      - boilerplate_net    

  # boilerplate-dbadmin:
  #   build:
  #     context: dbadmin
  #     dockerfile: Dockerfile    
  #   ports:
  #     - "8001:80"
  #   env_file: dbadmin/.env     
  #   ports:
  #     - "${PGADMIN_PORT:-9002}:80"
  #   networks:
  #     - boilerplate_net

networks:
  boilerplate_net:
    driver: bridge
