version: '3.5'

services:
  boilerplate-web:
    build:
      context: boilerplate
      dockerfile: Dockerfile_dev
    env_file: boilerplate/.env
    tty: true
    volumes:
      - ./boilerplate/:/app/
    ports:
      - "8000:8000"
    depends_on:
      - boilerplate-db
      - boilerplate-redis

  boilerplate-db:
    build:
      context: db
      dockerfile: Dockerfile
    env_file: db/.env     
    
  boilerplate-redis:
    image: "redis:5.0.7-alpine"   

  # boilerplate-dbadmin:
  #   build:
  #     context: dbadmin
  #     dockerfile: Dockerfile    
  #   ports:
  #     - "8001:80"
  #   env_file: dbadmin/.env     
  #   ports:
  #     - "${PGADMIN_PORT:-9002}:80"

# not used here.  
networks:
  boilerplate_net:
    driver: bridge
