#!/usr/bin/with-contenv sh
echo >&2 "starting CELERY"
exec cd /app/ celery -A boilerplate worker --beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --concurrency=2 -Ofair --loglevel=debug --task-events
