#!/usr/bin/with-contenv sh
echo >&2 "starting DJANGO"
exec cd /app/ gunicorn boilerplate.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 30 --worker-tmp-dir /dev/shm  --threads=4 --worker-class=gthread --max-requests 1000 --max-requests-jitter 200 --reload
