apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: boilerplate-letsencrypt-prod
spec:
  secretName: boilerplate-letsencrypt-prod
  duration: 24h
  renewBefore: 12h
  commonName: boilerplate.dev
  dnsNames:
  - boilerplate.dev
  - www.boilerplate.dev
  issuerRef:
    name: boilerplate-letsencrypt-prod 
    kind: ClusterIssuer
---    
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: boilerplate-letsencrypt-prod 
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: you@email.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: boilerplate-letsencrypt-prod 
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: boilerplate-ingress-class