# Use an official Python runtime as a parent image
FROM python:3.8.1-slim-buster
LABEL maintainer="aymen@eralabs.io"

ENV PYTHONUNBUFFERED 1
ENV S6_VERSION=v2.2.0.3

RUN apt-get update --yes --quiet && apt-get install --yes --quiet --no-install-recommends \
    build-essential \
    vim \   
    curl \
    iputils-ping \
    xz-utils     

COPY ./requirements.txt /app/requirements.txt
RUN pip install --upgrade pip && pip install -r /app/requirements.txt

COPY . /app/
WORKDIR /app/

EXPOSE 8000

# We are using https://github.com/just-containers/s6-overlay to run Celery and Django.
ADD https://github.com/just-containers/s6-overlay/releases/download/${S6_VERSION}/s6-overlay-amd64.tar.gz  /tmp
RUN gunzip -c /tmp/s6-overlay-amd64.tar.gz | tar -xf - -C /
COPY ./s6-overlay/services-dev /etc/services.d/

ENTRYPOINT ["/init"]